### ISSUE TITLE
User manual?

### ISSUE THREAD

**Issue by lizhiq16** [grimme-lab/xtbiff#1]
Is there introduction or manual about QCG algorithm and xtb-iff?

**Comment by cplett** [comment]
Hi,
The user manual for the QCG algorithms can be found [here](https://xtb-docs.readthedocs.io/en/latest/crestqcg.html).
For the stand-alone use of xtb-IFF, there exists currently no user manual. If it should be used with the QCG algorithm in `CREST`, it has to be added to the PATH variable so that it is accessible by calling `xtbiff`.
